// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID       int32
	Name     pgtype.Text
	Date     pgtype.Timestamptz
	Deadline pgtype.Timestamptz
	AdminID  int32
}

type Gift struct {
	ID              int32
	Name            pgtype.Text
	Link            pgtype.Text
	TargetAmount    pgtype.Int8
	Status          string
	ContractAddress pgtype.Text
	JettonAddress   pgtype.Text
	EventID         int32
	RecipientID     int32
	AdminID         int32
	CollectedAmount pgtype.Int8
}

type Participant struct {
	ID      int32
	Role    pgtype.Text
	UserID  int32
	EventID int32
}

type ParticipantGift struct {
	IsPaid          pgtype.Bool
	Amount          pgtype.Int8
	TransactionHash pgtype.Text
	ParticipantID   int32
	GiftID          int32
}

type User struct {
	ID            int64
	FirstName     pgtype.Text
	LastName      pgtype.Text
	Username      pgtype.Text
	CreatedAt     pgtype.Date
	LangCode      pgtype.Text
	WalletAddress pgtype.Text
}
