// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGiftLike = `-- name: AddGiftLike :exec
insert into giftlikes (user_id, gift_id)
values ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGiftLikeParams struct {
	UserID int32
	GiftID int32
}

func (q *Queries) AddGiftLike(ctx context.Context, arg AddGiftLikeParams) error {
	_, err := q.db.Exec(ctx, addGiftLike, arg.UserID, arg.GiftID)
	return err
}

const cancelGift = `-- name: CancelGift :execresult
update Gifts
set status = 'cancelled'
where contract_address = $1
`

func (q *Queries) CancelGift(ctx context.Context, contractAddress pgtype.Text) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, cancelGift, contractAddress)
}

const changeAdmin = `-- name: ChangeAdmin :exec
update Gifts
set admin_id = (select id
                from Users
                where wallet_address = $1
                limit 1)
where contract_address = $2
`

type ChangeAdminParams struct {
	WalletAddress   pgtype.Text
	ContractAddress pgtype.Text
}

func (q *Queries) ChangeAdmin(ctx context.Context, arg ChangeAdminParams) error {
	_, err := q.db.Exec(ctx, changeAdmin, arg.WalletAddress, arg.ContractAddress)
	return err
}

const changeTargetAmount = `-- name: ChangeTargetAmount :exec
update Gifts
set target_amount = $1
where contract_address = $2
`

type ChangeTargetAmountParams struct {
	TargetAmount    pgtype.Int8
	ContractAddress pgtype.Text
}

func (q *Queries) ChangeTargetAmount(ctx context.Context, arg ChangeTargetAmountParams) error {
	_, err := q.db.Exec(ctx, changeTargetAmount, arg.TargetAmount, arg.ContractAddress)
	return err
}

const checkEventJoinCodeExists = `-- name: CheckEventJoinCodeExists :one
select EXISTS (
    select 1
    from Events
    where join_code = $1
)
`

func (q *Queries) CheckEventJoinCodeExists(ctx context.Context, joinCode pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkEventJoinCodeExists, joinCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createEvent = `-- name: CreateEvent :one
insert into Events (name, date, deadline, admin_id, join_code)
values ($1, $2, $3, $4, $5)
returning id, name, date, deadline, admin_id, join_code
`

type CreateEventParams struct {
	Name     pgtype.Text
	Date     pgtype.Timestamptz
	Deadline pgtype.Timestamptz
	AdminID  int32
	JoinCode pgtype.Text
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.Date,
		arg.Deadline,
		arg.AdminID,
		arg.JoinCode,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Deadline,
		&i.AdminID,
		&i.JoinCode,
	)
	return i, err
}

const createGift = `-- name: CreateGift :one
insert into Gifts (name, link, target_amount,
                   contract_address, jetton_address,
                   event_id, recipient_id, admin_id, description, image_url)
values ($1, $2, $3,$4, $5,
        $6, $7, $8, $9, $10)
returning id, name, link, target_amount, status, contract_address, jetton_address, event_id, recipient_id, admin_id, collected_amount, description, image_url
`

type CreateGiftParams struct {
	Name            pgtype.Text
	Link            pgtype.Text
	TargetAmount    pgtype.Int8
	ContractAddress pgtype.Text
	JettonAddress   pgtype.Text
	EventID         int32
	RecipientID     int32
	AdminID         int32
	Description     pgtype.Text
	ImageUrl        pgtype.Text
}

func (q *Queries) CreateGift(ctx context.Context, arg CreateGiftParams) (Gift, error) {
	row := q.db.QueryRow(ctx, createGift,
		arg.Name,
		arg.Link,
		arg.TargetAmount,
		arg.ContractAddress,
		arg.JettonAddress,
		arg.EventID,
		arg.RecipientID,
		arg.AdminID,
		arg.Description,
		arg.ImageUrl,
	)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Link,
		&i.TargetAmount,
		&i.Status,
		&i.ContractAddress,
		&i.JettonAddress,
		&i.EventID,
		&i.RecipientID,
		&i.AdminID,
		&i.CollectedAmount,
		&i.Description,
		&i.ImageUrl,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
insert into Participants (role, user_id, event_id)
values ($1, $2, $3)
returning id, role, user_id, event_id
`

type CreateParticipantParams struct {
	Role    pgtype.Text
	UserID  int32
	EventID int32
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant, arg.Role, arg.UserID, arg.EventID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.UserID,
		&i.EventID,
	)
	return i, err
}

const createParticipantGift = `-- name: CreateParticipantGift :one
insert into Participant_Gift (is_paid, amount,
                              transaction_hash, participant_id, gift_id)
values ($1, $2, $3, $4, $5)
on conflict (transaction_hash) do nothing
returning is_paid, amount, transaction_hash, participant_id, gift_id
`

type CreateParticipantGiftParams struct {
	IsPaid          pgtype.Bool
	Amount          pgtype.Int8
	TransactionHash pgtype.Text
	ParticipantID   int32
	GiftID          int32
}

func (q *Queries) CreateParticipantGift(ctx context.Context, arg CreateParticipantGiftParams) (ParticipantGift, error) {
	row := q.db.QueryRow(ctx, createParticipantGift,
		arg.IsPaid,
		arg.Amount,
		arg.TransactionHash,
		arg.ParticipantID,
		arg.GiftID,
	)
	var i ParticipantGift
	err := row.Scan(
		&i.IsPaid,
		&i.Amount,
		&i.TransactionHash,
		&i.ParticipantID,
		&i.GiftID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into Users (first_name, last_name, username, lang_code, wallet_address)
values ($1, $2, $3, $4, $5)
returning id, first_name, last_name, username, created_at, lang_code, wallet_address
`

type CreateUserParams struct {
	FirstName     pgtype.Text
	LastName      pgtype.Text
	Username      pgtype.Text
	LangCode      pgtype.Text
	WalletAddress pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.LangCode,
		arg.WalletAddress,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.CreatedAt,
		&i.LangCode,
		&i.WalletAddress,
	)
	return i, err
}

const decreaseCollectedAmount = `-- name: DecreaseCollectedAmount :exec
update Gifts
set collected_amount = collected_amount - $1
where contract_address = $2
`

type DecreaseCollectedAmountParams struct {
	CollectedAmount pgtype.Int8
	ContractAddress pgtype.Text
}

func (q *Queries) DecreaseCollectedAmount(ctx context.Context, arg DecreaseCollectedAmountParams) error {
	_, err := q.db.Exec(ctx, decreaseCollectedAmount, arg.CollectedAmount, arg.ContractAddress)
	return err
}

const deleteEvent = `-- name: DeleteEvent :execrows
delete from events
where id = $1 and admin_id = $2
`

type DeleteEventParams struct {
	ID      int32
	AdminID int32
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.AdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGift = `-- name: DeleteGift :execrows
delete from gifts
where id = $1 and admin_id = $2
`

type DeleteGiftParams struct {
	ID      int32
	AdminID int32
}

func (q *Queries) DeleteGift(ctx context.Context, arg DeleteGiftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGift, arg.ID, arg.AdminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteParticipantGift = `-- name: DeleteParticipantGift :exec
delete
from participant_gift
    using participants, users, gifts
where participant_gift.participant_id = participants.id
  and participants.user_id = users.id
  and participant_gift.gift_id = gifts.id
  and gifts.contract_address = $1
  and users.wallet_address = $2
`

type DeleteParticipantGiftParams struct {
	ContractAddress pgtype.Text
	WalletAddress   pgtype.Text
}

func (q *Queries) DeleteParticipantGift(ctx context.Context, arg DeleteParticipantGiftParams) error {
	_, err := q.db.Exec(ctx, deleteParticipantGift, arg.ContractAddress, arg.WalletAddress)
	return err
}

const getAllActiveGiftsAddresses = `-- name: GetAllActiveGiftsAddresses :many
select contract_address
from Gifts
where status = 'active'
`

func (q *Queries) GetAllActiveGiftsAddresses(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getAllActiveGiftsAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var contract_address pgtype.Text
		if err := rows.Scan(&contract_address); err != nil {
			return nil, err
		}
		items = append(items, contract_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllParticipantsOfGift = `-- name: GetAllParticipantsOfGift :many
select id, role, user_id, event_id, is_paid, amount, transaction_hash, participant_id, gift_id
from Participants
         inner join Participant_gift as pg on Participants.id = pg.participant_id
where pg.gift_id = $1
`

type GetAllParticipantsOfGiftRow struct {
	ID              int32
	Role            pgtype.Text
	UserID          int32
	EventID         int32
	IsPaid          pgtype.Bool
	Amount          pgtype.Int8
	TransactionHash pgtype.Text
	ParticipantID   int32
	GiftID          int32
}

func (q *Queries) GetAllParticipantsOfGift(ctx context.Context, giftID int32) ([]GetAllParticipantsOfGiftRow, error) {
	rows, err := q.db.Query(ctx, getAllParticipantsOfGift, giftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllParticipantsOfGiftRow
	for rows.Next() {
		var i GetAllParticipantsOfGiftRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.UserID,
			&i.EventID,
			&i.IsPaid,
			&i.Amount,
			&i.TransactionHash,
			&i.ParticipantID,
			&i.GiftID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByJoinCode = `-- name: GetEventByJoinCode :one
select 1 from events
where join_code = $1
`

func (q *Queries) GetEventByJoinCode(ctx context.Context, joinCode pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, getEventByJoinCode, joinCode)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getEventsInfoByUserID = `-- name: GetEventsInfoByUserID :many
select
    e.id,
    e.name,
    e.date,
    e.deadline,
    e.admin_id,
    count(distinct p.id)::int as participants_count
from events e
         left join participants p on p.event_id = e.id
where e.admin_id = $1
   or e.id in (
    select event_id
    from participants
    where user_id = $1
)
group by e.id, e.name, e.date, e.deadline, e.admin_id
order by e.date asc
`

type GetEventsInfoByUserIDRow struct {
	ID                int32
	Name              pgtype.Text
	Date              pgtype.Timestamptz
	Deadline          pgtype.Timestamptz
	AdminID           int32
	ParticipantsCount int32
}

func (q *Queries) GetEventsInfoByUserID(ctx context.Context, adminID int32) ([]GetEventsInfoByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getEventsInfoByUserID, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsInfoByUserIDRow
	for rows.Next() {
		var i GetEventsInfoByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Deadline,
			&i.AdminID,
			&i.ParticipantsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGiftByContract = `-- name: GetGiftByContract :one
select id, name, link, target_amount, status, contract_address, jetton_address, event_id, recipient_id, admin_id, collected_amount, description, image_url
from Gifts
where Gifts.contract_address = $1
limit 1
`

func (q *Queries) GetGiftByContract(ctx context.Context, contractAddress pgtype.Text) (Gift, error) {
	row := q.db.QueryRow(ctx, getGiftByContract, contractAddress)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Link,
		&i.TargetAmount,
		&i.Status,
		&i.ContractAddress,
		&i.JettonAddress,
		&i.EventID,
		&i.RecipientID,
		&i.AdminID,
		&i.CollectedAmount,
		&i.Description,
		&i.ImageUrl,
	)
	return i, err
}

const getGiftRecipientsOfCurrentEvent = `-- name: GetGiftRecipientsOfCurrentEvent :many
select p.id, u.first_name, u.last_name
from participants p
         join users u on u.id = p.user_id
where p.event_id = $1
  and p.role = 'recipient'
`

type GetGiftRecipientsOfCurrentEventRow struct {
	ID        int32
	FirstName pgtype.Text
	LastName  pgtype.Text
}

func (q *Queries) GetGiftRecipientsOfCurrentEvent(ctx context.Context, eventID int32) ([]GetGiftRecipientsOfCurrentEventRow, error) {
	rows, err := q.db.Query(ctx, getGiftRecipientsOfCurrentEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGiftRecipientsOfCurrentEventRow
	for rows.Next() {
		var i GetGiftRecipientsOfCurrentEventRow
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGifts = `-- name: GetGifts :many
select id, name, link, target_amount, status, contract_address, jetton_address, event_id, recipient_id, admin_id, collected_amount, description, image_url from Gifts
`

func (q *Queries) GetGifts(ctx context.Context) ([]Gift, error) {
	rows, err := q.db.Query(ctx, getGifts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gift
	for rows.Next() {
		var i Gift
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Link,
			&i.TargetAmount,
			&i.Status,
			&i.ContractAddress,
			&i.JettonAddress,
			&i.EventID,
			&i.RecipientID,
			&i.AdminID,
			&i.CollectedAmount,
			&i.Description,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGiftsInfoByRecipient = `-- name: GetGiftsInfoByRecipient :many
select g.id, g.name, g.link, g.target_amount, g.status, g.contract_address, g.jetton_address, g.event_id, g.recipient_id, g.admin_id, g.collected_amount, g.description, g.image_url,
       (select count(*) from giftlikes where giftlikes.gift_id = g.id) as likes_amount,
                               exists(select 1 from giftlikes where giftlikes.user_id = $1 and giftlikes.gift_id = g.id)
from Gifts g
where g.recipient_id = $2
`

type GetGiftsInfoByRecipientParams struct {
	UserID      int32
	RecipientID int32
}

type GetGiftsInfoByRecipientRow struct {
	ID              int32
	Name            pgtype.Text
	Link            pgtype.Text
	TargetAmount    pgtype.Int8
	Status          string
	ContractAddress pgtype.Text
	JettonAddress   pgtype.Text
	EventID         int32
	RecipientID     int32
	AdminID         int32
	CollectedAmount pgtype.Int8
	Description     pgtype.Text
	ImageUrl        pgtype.Text
	LikesAmount     int64
	Exists          bool
}

func (q *Queries) GetGiftsInfoByRecipient(ctx context.Context, arg GetGiftsInfoByRecipientParams) ([]GetGiftsInfoByRecipientRow, error) {
	rows, err := q.db.Query(ctx, getGiftsInfoByRecipient, arg.UserID, arg.RecipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGiftsInfoByRecipientRow
	for rows.Next() {
		var i GetGiftsInfoByRecipientRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Link,
			&i.TargetAmount,
			&i.Status,
			&i.ContractAddress,
			&i.JettonAddress,
			&i.EventID,
			&i.RecipientID,
			&i.AdminID,
			&i.CollectedAmount,
			&i.Description,
			&i.ImageUrl,
			&i.LikesAmount,
			&i.Exists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBasicInfo = `-- name: GetUserBasicInfo :one
select first_name, last_name, username
from users
where id = $1
limit 1
`

type GetUserBasicInfoRow struct {
	FirstName pgtype.Text
	LastName  pgtype.Text
	Username  pgtype.Text
}

func (q *Queries) GetUserBasicInfo(ctx context.Context, id int64) (GetUserBasicInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserBasicInfo, id)
	var i GetUserBasicInfoRow
	err := row.Scan(&i.FirstName, &i.LastName, &i.Username)
	return i, err
}

const increaseCollectedAmount = `-- name: IncreaseCollectedAmount :exec
update Gifts
set collected_amount = collected_amount - $1
where contract_address = $2
`

type IncreaseCollectedAmountParams struct {
	CollectedAmount pgtype.Int8
	ContractAddress pgtype.Text
}

func (q *Queries) IncreaseCollectedAmount(ctx context.Context, arg IncreaseCollectedAmountParams) error {
	_, err := q.db.Exec(ctx, increaseCollectedAmount, arg.CollectedAmount, arg.ContractAddress)
	return err
}

const isActiveGift = `-- name: IsActiveGift :one
select exists(select 1
              from Gifts
              where contract_address = $1
                and status = 'active')
`

func (q *Queries) IsActiveGift(ctx context.Context, contractAddress pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveGift, contractAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordTransfer = `-- name: RecordTransfer :exec
insert into participant_gift (participant_id, gift_id, amount, transaction_hash, is_paid)
values ((select participants.id
         from participants
                  join users on participants.user_id = users.id
         where users.wallet_address = $1
           and participants.event_id = (select event_id
                                        from gifts
                                        where gifts.contract_address = $2)
         limit 1),
        (select id from Gifts where contract_address = $2),
        $3, $4, true)
on conflict (transaction_hash) do nothing
`

type RecordTransferParams struct {
	WalletAddress   pgtype.Text
	ContractAddress pgtype.Text
	Amount          pgtype.Int8
	TransactionHash pgtype.Text
}

func (q *Queries) RecordTransfer(ctx context.Context, arg RecordTransferParams) error {
	_, err := q.db.Exec(ctx, recordTransfer,
		arg.WalletAddress,
		arg.ContractAddress,
		arg.Amount,
		arg.TransactionHash,
	)
	return err
}

const removeGiftLike = `-- name: RemoveGiftLike :exec
delete from giftlikes
WHERE user_id = $1 AND gift_id = $2
`

type RemoveGiftLikeParams struct {
	UserID int32
	GiftID int32
}

func (q *Queries) RemoveGiftLike(ctx context.Context, arg RemoveGiftLikeParams) error {
	_, err := q.db.Exec(ctx, removeGiftLike, arg.UserID, arg.GiftID)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
update events
set name = $1,
    date = $2,
    deadline = $3
where id = $4 and admin_id = $5
returning id, name, date, deadline, admin_id
`

type UpdateEventParams struct {
	Name     pgtype.Text
	Date     pgtype.Timestamptz
	Deadline pgtype.Timestamptz
	ID       int32
	AdminID  int32
}

type UpdateEventRow struct {
	ID       int32
	Name     pgtype.Text
	Date     pgtype.Timestamptz
	Deadline pgtype.Timestamptz
	AdminID  int32
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.Name,
		arg.Date,
		arg.Deadline,
		arg.ID,
		arg.AdminID,
	)
	var i UpdateEventRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Deadline,
		&i.AdminID,
	)
	return i, err
}

const updateGift = `-- name: UpdateGift :one
update gifts
set name = $1,
    description = $2,
    target_amount = $3,
    link = $4
where id = $5 and admin_id = $6
returning id, name, description, target_amount, link
`

type UpdateGiftParams struct {
	Name         pgtype.Text
	Description  pgtype.Text
	TargetAmount pgtype.Int8
	Link         pgtype.Text
	ID           int32
	AdminID      int32
}

type UpdateGiftRow struct {
	ID           int32
	Name         pgtype.Text
	Description  pgtype.Text
	TargetAmount pgtype.Int8
	Link         pgtype.Text
}

func (q *Queries) UpdateGift(ctx context.Context, arg UpdateGiftParams) (UpdateGiftRow, error) {
	row := q.db.QueryRow(ctx, updateGift,
		arg.Name,
		arg.Description,
		arg.TargetAmount,
		arg.Link,
		arg.ID,
		arg.AdminID,
	)
	var i UpdateGiftRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TargetAmount,
		&i.Link,
	)
	return i, err
}
